SELECT TOP (1000) [store_id]
      ,[store_name]
      ,[store_type]
      ,[address]
      ,[city]
      ,[state]
      ,[state_full]
      ,[zip_code]
      ,[country]
      ,[region]
      ,[district]
      ,[phone]
      ,[manager_name]
      ,[opened_date]
      ,[sq_footage]
      ,[num_employees]
      ,[annual_rent_usd]
      ,[is_active]
      ,[has_parking]
      ,[has_cafe]
  FROM .[bronze].[stores]