SELECT TOP (1000) [return_id]
      ,[original_txn_id]
      ,[original_order_id]
      ,[customer_id]
      ,[customer_name]
      ,[product_id]
      ,[product_name]
      ,[quantity_returned]
      ,[return_date]
      ,[return_reason]
      ,[refund_amount]
      ,[refund_method]
      ,[return_channel]
      ,[restocked]
      ,[return_status]
      ,[handled_by_emp_id]
      ,[notes]
  FROM [bronze].[returns]